# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/src/mapserver/mapserver-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/src/mapserver/mapserver-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/mapserver/mapserver-master/CMakeFiles /usr/src/mapserver/mapserver-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/mapserver/mapserver-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named legend

# Build rule for target.
legend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 legend
.PHONY : legend

# fast build rule for target.
legend/fast:
	$(MAKE) -f CMakeFiles/legend.dir/build.make CMakeFiles/legend.dir/build
.PHONY : legend/fast

#=============================================================================
# Target rules for targets named mapserv

# Build rule for target.
mapserv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapserv
.PHONY : mapserv

# fast build rule for target.
mapserv/fast:
	$(MAKE) -f CMakeFiles/mapserv.dir/build.make CMakeFiles/mapserv.dir/build
.PHONY : mapserv/fast

#=============================================================================
# Target rules for targets named mapserver

# Build rule for target.
mapserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapserver
.PHONY : mapserver

# fast build rule for target.
mapserver/fast:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/build
.PHONY : mapserver/fast

#=============================================================================
# Target rules for targets named msencrypt

# Build rule for target.
msencrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msencrypt
.PHONY : msencrypt

# fast build rule for target.
msencrypt/fast:
	$(MAKE) -f CMakeFiles/msencrypt.dir/build.make CMakeFiles/msencrypt.dir/build
.PHONY : msencrypt/fast

#=============================================================================
# Target rules for targets named scalebar

# Build rule for target.
scalebar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scalebar
.PHONY : scalebar

# fast build rule for target.
scalebar/fast:
	$(MAKE) -f CMakeFiles/scalebar.dir/build.make CMakeFiles/scalebar.dir/build
.PHONY : scalebar/fast

#=============================================================================
# Target rules for targets named shp2img

# Build rule for target.
shp2img: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shp2img
.PHONY : shp2img

# fast build rule for target.
shp2img/fast:
	$(MAKE) -f CMakeFiles/shp2img.dir/build.make CMakeFiles/shp2img.dir/build
.PHONY : shp2img/fast

#=============================================================================
# Target rules for targets named shptree

# Build rule for target.
shptree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shptree
.PHONY : shptree

# fast build rule for target.
shptree/fast:
	$(MAKE) -f CMakeFiles/shptree.dir/build.make CMakeFiles/shptree.dir/build
.PHONY : shptree/fast

#=============================================================================
# Target rules for targets named shptreevis

# Build rule for target.
shptreevis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shptreevis
.PHONY : shptreevis

# fast build rule for target.
shptreevis/fast:
	$(MAKE) -f CMakeFiles/shptreevis.dir/build.make CMakeFiles/shptreevis.dir/build
.PHONY : shptreevis/fast

#=============================================================================
# Target rules for targets named sortshp

# Build rule for target.
sortshp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sortshp
.PHONY : sortshp

# fast build rule for target.
sortshp/fast:
	$(MAKE) -f CMakeFiles/sortshp.dir/build.make CMakeFiles/sortshp.dir/build
.PHONY : sortshp/fast

#=============================================================================
# Target rules for targets named tile4ms

# Build rule for target.
tile4ms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tile4ms
.PHONY : tile4ms

# fast build rule for target.
tile4ms/fast:
	$(MAKE) -f CMakeFiles/tile4ms.dir/build.make CMakeFiles/tile4ms.dir/build
.PHONY : tile4ms/fast

#=============================================================================
# Target rules for targets named _pythonmapscript

# Build rule for target.
_pythonmapscript: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _pythonmapscript
.PHONY : _pythonmapscript

# fast build rule for target.
_pythonmapscript/fast:
	$(MAKE) -f mapscript/python/CMakeFiles/_pythonmapscript.dir/build.make mapscript/python/CMakeFiles/_pythonmapscript.dir/build
.PHONY : _pythonmapscript/fast

cgiutil.o: cgiutil.c.o
.PHONY : cgiutil.o

# target to build an object file
cgiutil.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/cgiutil.c.o
.PHONY : cgiutil.c.o

cgiutil.i: cgiutil.c.i
.PHONY : cgiutil.i

# target to preprocess a source file
cgiutil.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/cgiutil.c.i
.PHONY : cgiutil.c.i

cgiutil.s: cgiutil.c.s
.PHONY : cgiutil.s

# target to generate assembly for a file
cgiutil.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/cgiutil.c.s
.PHONY : cgiutil.c.s

classobject.o: classobject.c.o
.PHONY : classobject.o

# target to build an object file
classobject.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/classobject.c.o
.PHONY : classobject.c.o

classobject.i: classobject.c.i
.PHONY : classobject.i

# target to preprocess a source file
classobject.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/classobject.c.i
.PHONY : classobject.c.i

classobject.s: classobject.c.s
.PHONY : classobject.s

# target to generate assembly for a file
classobject.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/classobject.c.s
.PHONY : classobject.c.s

hittest.o: hittest.c.o
.PHONY : hittest.o

# target to build an object file
hittest.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/hittest.c.o
.PHONY : hittest.c.o

hittest.i: hittest.c.i
.PHONY : hittest.i

# target to preprocess a source file
hittest.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/hittest.c.i
.PHONY : hittest.c.i

hittest.s: hittest.c.s
.PHONY : hittest.s

# target to generate assembly for a file
hittest.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/hittest.c.s
.PHONY : hittest.c.s

layerobject.o: layerobject.c.o
.PHONY : layerobject.o

# target to build an object file
layerobject.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/layerobject.c.o
.PHONY : layerobject.c.o

layerobject.i: layerobject.c.i
.PHONY : layerobject.i

# target to preprocess a source file
layerobject.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/layerobject.c.i
.PHONY : layerobject.c.i

layerobject.s: layerobject.c.s
.PHONY : layerobject.s

# target to generate assembly for a file
layerobject.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/layerobject.c.s
.PHONY : layerobject.c.s

legend.o: legend.c.o
.PHONY : legend.o

# target to build an object file
legend.c.o:
	$(MAKE) -f CMakeFiles/legend.dir/build.make CMakeFiles/legend.dir/legend.c.o
.PHONY : legend.c.o

legend.i: legend.c.i
.PHONY : legend.i

# target to preprocess a source file
legend.c.i:
	$(MAKE) -f CMakeFiles/legend.dir/build.make CMakeFiles/legend.dir/legend.c.i
.PHONY : legend.c.i

legend.s: legend.c.s
.PHONY : legend.s

# target to generate assembly for a file
legend.c.s:
	$(MAKE) -f CMakeFiles/legend.dir/build.make CMakeFiles/legend.dir/legend.c.s
.PHONY : legend.c.s

mapagg.o: mapagg.cpp.o
.PHONY : mapagg.o

# target to build an object file
mapagg.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapagg.cpp.o
.PHONY : mapagg.cpp.o

mapagg.i: mapagg.cpp.i
.PHONY : mapagg.i

# target to preprocess a source file
mapagg.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapagg.cpp.i
.PHONY : mapagg.cpp.i

mapagg.s: mapagg.cpp.s
.PHONY : mapagg.s

# target to generate assembly for a file
mapagg.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapagg.cpp.s
.PHONY : mapagg.cpp.s

mapbits.o: mapbits.c.o
.PHONY : mapbits.o

# target to build an object file
mapbits.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapbits.c.o
.PHONY : mapbits.c.o

mapbits.i: mapbits.c.i
.PHONY : mapbits.i

# target to preprocess a source file
mapbits.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapbits.c.i
.PHONY : mapbits.c.i

mapbits.s: mapbits.c.s
.PHONY : mapbits.s

# target to generate assembly for a file
mapbits.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapbits.c.s
.PHONY : mapbits.c.s

mapcairo.o: mapcairo.c.o
.PHONY : mapcairo.o

# target to build an object file
mapcairo.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcairo.c.o
.PHONY : mapcairo.c.o

mapcairo.i: mapcairo.c.i
.PHONY : mapcairo.i

# target to preprocess a source file
mapcairo.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcairo.c.i
.PHONY : mapcairo.c.i

mapcairo.s: mapcairo.c.s
.PHONY : mapcairo.s

# target to generate assembly for a file
mapcairo.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcairo.c.s
.PHONY : mapcairo.c.s

mapchart.o: mapchart.c.o
.PHONY : mapchart.o

# target to build an object file
mapchart.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapchart.c.o
.PHONY : mapchart.c.o

mapchart.i: mapchart.c.i
.PHONY : mapchart.i

# target to preprocess a source file
mapchart.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapchart.c.i
.PHONY : mapchart.c.i

mapchart.s: mapchart.c.s
.PHONY : mapchart.s

# target to generate assembly for a file
mapchart.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapchart.c.s
.PHONY : mapchart.c.s

mapcluster.o: mapcluster.c.o
.PHONY : mapcluster.o

# target to build an object file
mapcluster.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcluster.c.o
.PHONY : mapcluster.c.o

mapcluster.i: mapcluster.c.i
.PHONY : mapcluster.i

# target to preprocess a source file
mapcluster.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcluster.c.i
.PHONY : mapcluster.c.i

mapcluster.s: mapcluster.c.s
.PHONY : mapcluster.s

# target to generate assembly for a file
mapcluster.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcluster.c.s
.PHONY : mapcluster.c.s

mapcontext.o: mapcontext.c.o
.PHONY : mapcontext.o

# target to build an object file
mapcontext.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcontext.c.o
.PHONY : mapcontext.c.o

mapcontext.i: mapcontext.c.i
.PHONY : mapcontext.i

# target to preprocess a source file
mapcontext.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcontext.c.i
.PHONY : mapcontext.c.i

mapcontext.s: mapcontext.c.s
.PHONY : mapcontext.s

# target to generate assembly for a file
mapcontext.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcontext.c.s
.PHONY : mapcontext.c.s

mapcontour.o: mapcontour.c.o
.PHONY : mapcontour.o

# target to build an object file
mapcontour.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcontour.c.o
.PHONY : mapcontour.c.o

mapcontour.i: mapcontour.c.i
.PHONY : mapcontour.i

# target to preprocess a source file
mapcontour.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcontour.c.i
.PHONY : mapcontour.c.i

mapcontour.s: mapcontour.c.s
.PHONY : mapcontour.s

# target to generate assembly for a file
mapcontour.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcontour.c.s
.PHONY : mapcontour.c.s

mapcopy.o: mapcopy.c.o
.PHONY : mapcopy.o

# target to build an object file
mapcopy.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcopy.c.o
.PHONY : mapcopy.c.o

mapcopy.i: mapcopy.c.i
.PHONY : mapcopy.i

# target to preprocess a source file
mapcopy.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcopy.c.i
.PHONY : mapcopy.c.i

mapcopy.s: mapcopy.c.s
.PHONY : mapcopy.s

# target to generate assembly for a file
mapcopy.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcopy.c.s
.PHONY : mapcopy.c.s

mapcpl.o: mapcpl.c.o
.PHONY : mapcpl.o

# target to build an object file
mapcpl.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcpl.c.o
.PHONY : mapcpl.c.o

mapcpl.i: mapcpl.c.i
.PHONY : mapcpl.i

# target to preprocess a source file
mapcpl.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcpl.c.i
.PHONY : mapcpl.c.i

mapcpl.s: mapcpl.c.s
.PHONY : mapcpl.s

# target to generate assembly for a file
mapcpl.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcpl.c.s
.PHONY : mapcpl.c.s

mapcrypto.o: mapcrypto.c.o
.PHONY : mapcrypto.o

# target to build an object file
mapcrypto.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcrypto.c.o
.PHONY : mapcrypto.c.o

mapcrypto.i: mapcrypto.c.i
.PHONY : mapcrypto.i

# target to preprocess a source file
mapcrypto.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcrypto.c.i
.PHONY : mapcrypto.c.i

mapcrypto.s: mapcrypto.c.s
.PHONY : mapcrypto.s

# target to generate assembly for a file
mapcrypto.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapcrypto.c.s
.PHONY : mapcrypto.c.s

mapdebug.o: mapdebug.c.o
.PHONY : mapdebug.o

# target to build an object file
mapdebug.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdebug.c.o
.PHONY : mapdebug.c.o

mapdebug.i: mapdebug.c.i
.PHONY : mapdebug.i

# target to preprocess a source file
mapdebug.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdebug.c.i
.PHONY : mapdebug.c.i

mapdebug.s: mapdebug.c.s
.PHONY : mapdebug.s

# target to generate assembly for a file
mapdebug.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdebug.c.s
.PHONY : mapdebug.c.s

mapdraw.o: mapdraw.c.o
.PHONY : mapdraw.o

# target to build an object file
mapdraw.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdraw.c.o
.PHONY : mapdraw.c.o

mapdraw.i: mapdraw.c.i
.PHONY : mapdraw.i

# target to preprocess a source file
mapdraw.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdraw.c.i
.PHONY : mapdraw.c.i

mapdraw.s: mapdraw.c.s
.PHONY : mapdraw.s

# target to generate assembly for a file
mapdraw.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdraw.c.s
.PHONY : mapdraw.c.s

mapdrawgdal.o: mapdrawgdal.c.o
.PHONY : mapdrawgdal.o

# target to build an object file
mapdrawgdal.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdrawgdal.c.o
.PHONY : mapdrawgdal.c.o

mapdrawgdal.i: mapdrawgdal.c.i
.PHONY : mapdrawgdal.i

# target to preprocess a source file
mapdrawgdal.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdrawgdal.c.i
.PHONY : mapdrawgdal.c.i

mapdrawgdal.s: mapdrawgdal.c.s
.PHONY : mapdrawgdal.s

# target to generate assembly for a file
mapdrawgdal.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdrawgdal.c.s
.PHONY : mapdrawgdal.c.s

mapdummyrenderer.o: mapdummyrenderer.c.o
.PHONY : mapdummyrenderer.o

# target to build an object file
mapdummyrenderer.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdummyrenderer.c.o
.PHONY : mapdummyrenderer.c.o

mapdummyrenderer.i: mapdummyrenderer.c.i
.PHONY : mapdummyrenderer.i

# target to preprocess a source file
mapdummyrenderer.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdummyrenderer.c.i
.PHONY : mapdummyrenderer.c.i

mapdummyrenderer.s: mapdummyrenderer.c.s
.PHONY : mapdummyrenderer.s

# target to generate assembly for a file
mapdummyrenderer.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapdummyrenderer.c.s
.PHONY : mapdummyrenderer.c.s

maperror.o: maperror.c.o
.PHONY : maperror.o

# target to build an object file
maperror.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maperror.c.o
.PHONY : maperror.c.o

maperror.i: maperror.c.i
.PHONY : maperror.i

# target to preprocess a source file
maperror.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maperror.c.i
.PHONY : maperror.c.i

maperror.s: maperror.c.s
.PHONY : maperror.s

# target to generate assembly for a file
maperror.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maperror.c.s
.PHONY : maperror.c.s

mapfile.o: mapfile.c.o
.PHONY : mapfile.o

# target to build an object file
mapfile.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapfile.c.o
.PHONY : mapfile.c.o

mapfile.i: mapfile.c.i
.PHONY : mapfile.i

# target to preprocess a source file
mapfile.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapfile.c.i
.PHONY : mapfile.c.i

mapfile.s: mapfile.c.s
.PHONY : mapfile.s

# target to generate assembly for a file
mapfile.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapfile.c.s
.PHONY : mapfile.c.s

mapgd.o: mapgd.c.o
.PHONY : mapgd.o

# target to build an object file
mapgd.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgd.c.o
.PHONY : mapgd.c.o

mapgd.i: mapgd.c.i
.PHONY : mapgd.i

# target to preprocess a source file
mapgd.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgd.c.i
.PHONY : mapgd.c.i

mapgd.s: mapgd.c.s
.PHONY : mapgd.s

# target to generate assembly for a file
mapgd.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgd.c.s
.PHONY : mapgd.c.s

mapgdal.o: mapgdal.c.o
.PHONY : mapgdal.o

# target to build an object file
mapgdal.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgdal.c.o
.PHONY : mapgdal.c.o

mapgdal.i: mapgdal.c.i
.PHONY : mapgdal.i

# target to preprocess a source file
mapgdal.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgdal.c.i
.PHONY : mapgdal.c.i

mapgdal.s: mapgdal.c.s
.PHONY : mapgdal.s

# target to generate assembly for a file
mapgdal.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgdal.c.s
.PHONY : mapgdal.c.s

mapgeomtransform.o: mapgeomtransform.c.o
.PHONY : mapgeomtransform.o

# target to build an object file
mapgeomtransform.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeomtransform.c.o
.PHONY : mapgeomtransform.c.o

mapgeomtransform.i: mapgeomtransform.c.i
.PHONY : mapgeomtransform.i

# target to preprocess a source file
mapgeomtransform.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeomtransform.c.i
.PHONY : mapgeomtransform.c.i

mapgeomtransform.s: mapgeomtransform.c.s
.PHONY : mapgeomtransform.s

# target to generate assembly for a file
mapgeomtransform.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeomtransform.c.s
.PHONY : mapgeomtransform.c.s

mapgeomutil.o: mapgeomutil.cpp.o
.PHONY : mapgeomutil.o

# target to build an object file
mapgeomutil.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeomutil.cpp.o
.PHONY : mapgeomutil.cpp.o

mapgeomutil.i: mapgeomutil.cpp.i
.PHONY : mapgeomutil.i

# target to preprocess a source file
mapgeomutil.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeomutil.cpp.i
.PHONY : mapgeomutil.cpp.i

mapgeomutil.s: mapgeomutil.cpp.s
.PHONY : mapgeomutil.s

# target to generate assembly for a file
mapgeomutil.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeomutil.cpp.s
.PHONY : mapgeomutil.cpp.s

mapgeos.o: mapgeos.c.o
.PHONY : mapgeos.o

# target to build an object file
mapgeos.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeos.c.o
.PHONY : mapgeos.c.o

mapgeos.i: mapgeos.c.i
.PHONY : mapgeos.i

# target to preprocess a source file
mapgeos.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeos.c.i
.PHONY : mapgeos.c.i

mapgeos.s: mapgeos.c.s
.PHONY : mapgeos.s

# target to generate assembly for a file
mapgeos.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgeos.c.s
.PHONY : mapgeos.c.s

mapgml.o: mapgml.c.o
.PHONY : mapgml.o

# target to build an object file
mapgml.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgml.c.o
.PHONY : mapgml.c.o

mapgml.i: mapgml.c.i
.PHONY : mapgml.i

# target to preprocess a source file
mapgml.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgml.c.i
.PHONY : mapgml.c.i

mapgml.s: mapgml.c.s
.PHONY : mapgml.s

# target to generate assembly for a file
mapgml.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgml.c.s
.PHONY : mapgml.c.s

mapgraticule.o: mapgraticule.c.o
.PHONY : mapgraticule.o

# target to build an object file
mapgraticule.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgraticule.c.o
.PHONY : mapgraticule.c.o

mapgraticule.i: mapgraticule.c.i
.PHONY : mapgraticule.i

# target to preprocess a source file
mapgraticule.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgraticule.c.i
.PHONY : mapgraticule.c.i

mapgraticule.s: mapgraticule.c.s
.PHONY : mapgraticule.s

# target to generate assembly for a file
mapgraticule.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapgraticule.c.s
.PHONY : mapgraticule.c.s

maphash.o: maphash.c.o
.PHONY : maphash.o

# target to build an object file
maphash.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maphash.c.o
.PHONY : maphash.c.o

maphash.i: maphash.c.i
.PHONY : maphash.i

# target to preprocess a source file
maphash.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maphash.c.i
.PHONY : maphash.c.i

maphash.s: maphash.c.s
.PHONY : maphash.s

# target to generate assembly for a file
maphash.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maphash.c.s
.PHONY : maphash.c.s

maphttp.o: maphttp.c.o
.PHONY : maphttp.o

# target to build an object file
maphttp.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maphttp.c.o
.PHONY : maphttp.c.o

maphttp.i: maphttp.c.i
.PHONY : maphttp.i

# target to preprocess a source file
maphttp.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maphttp.c.i
.PHONY : maphttp.c.i

maphttp.s: maphttp.c.s
.PHONY : maphttp.s

# target to generate assembly for a file
maphttp.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maphttp.c.s
.PHONY : maphttp.c.s

mapimageio.o: mapimageio.c.o
.PHONY : mapimageio.o

# target to build an object file
mapimageio.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapimageio.c.o
.PHONY : mapimageio.c.o

mapimageio.i: mapimageio.c.i
.PHONY : mapimageio.i

# target to preprocess a source file
mapimageio.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapimageio.c.i
.PHONY : mapimageio.c.i

mapimageio.s: mapimageio.c.s
.PHONY : mapimageio.s

# target to generate assembly for a file
mapimageio.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapimageio.c.s
.PHONY : mapimageio.c.s

mapimagemap.o: mapimagemap.c.o
.PHONY : mapimagemap.o

# target to build an object file
mapimagemap.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapimagemap.c.o
.PHONY : mapimagemap.c.o

mapimagemap.i: mapimagemap.c.i
.PHONY : mapimagemap.i

# target to preprocess a source file
mapimagemap.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapimagemap.c.i
.PHONY : mapimagemap.c.i

mapimagemap.s: mapimagemap.c.s
.PHONY : mapimagemap.s

# target to generate assembly for a file
mapimagemap.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapimagemap.c.s
.PHONY : mapimagemap.c.s

mapio.o: mapio.c.o
.PHONY : mapio.o

# target to build an object file
mapio.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapio.c.o
.PHONY : mapio.c.o

mapio.i: mapio.c.i
.PHONY : mapio.i

# target to preprocess a source file
mapio.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapio.c.i
.PHONY : mapio.c.i

mapio.s: mapio.c.s
.PHONY : mapio.s

# target to generate assembly for a file
mapio.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapio.c.s
.PHONY : mapio.c.s

mapjoin.o: mapjoin.c.o
.PHONY : mapjoin.o

# target to build an object file
mapjoin.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapjoin.c.o
.PHONY : mapjoin.c.o

mapjoin.i: mapjoin.c.i
.PHONY : mapjoin.i

# target to preprocess a source file
mapjoin.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapjoin.c.i
.PHONY : mapjoin.c.i

mapjoin.s: mapjoin.c.s
.PHONY : mapjoin.s

# target to generate assembly for a file
mapjoin.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapjoin.c.s
.PHONY : mapjoin.c.s

mapkml.o: mapkml.cpp.o
.PHONY : mapkml.o

# target to build an object file
mapkml.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapkml.cpp.o
.PHONY : mapkml.cpp.o

mapkml.i: mapkml.cpp.i
.PHONY : mapkml.i

# target to preprocess a source file
mapkml.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapkml.cpp.i
.PHONY : mapkml.cpp.i

mapkml.s: mapkml.cpp.s
.PHONY : mapkml.s

# target to generate assembly for a file
mapkml.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapkml.cpp.s
.PHONY : mapkml.cpp.s

mapkmlrenderer.o: mapkmlrenderer.cpp.o
.PHONY : mapkmlrenderer.o

# target to build an object file
mapkmlrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapkmlrenderer.cpp.o
.PHONY : mapkmlrenderer.cpp.o

mapkmlrenderer.i: mapkmlrenderer.cpp.i
.PHONY : mapkmlrenderer.i

# target to preprocess a source file
mapkmlrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapkmlrenderer.cpp.i
.PHONY : mapkmlrenderer.cpp.i

mapkmlrenderer.s: mapkmlrenderer.cpp.s
.PHONY : mapkmlrenderer.s

# target to generate assembly for a file
mapkmlrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapkmlrenderer.cpp.s
.PHONY : mapkmlrenderer.cpp.s

maplabel.o: maplabel.c.o
.PHONY : maplabel.o

# target to build an object file
maplabel.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplabel.c.o
.PHONY : maplabel.c.o

maplabel.i: maplabel.c.i
.PHONY : maplabel.i

# target to preprocess a source file
maplabel.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplabel.c.i
.PHONY : maplabel.c.i

maplabel.s: maplabel.c.s
.PHONY : maplabel.s

# target to generate assembly for a file
maplabel.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplabel.c.s
.PHONY : maplabel.c.s

maplayer.o: maplayer.c.o
.PHONY : maplayer.o

# target to build an object file
maplayer.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplayer.c.o
.PHONY : maplayer.c.o

maplayer.i: maplayer.c.i
.PHONY : maplayer.i

# target to preprocess a source file
maplayer.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplayer.c.i
.PHONY : maplayer.c.i

maplayer.s: maplayer.c.s
.PHONY : maplayer.s

# target to generate assembly for a file
maplayer.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplayer.c.s
.PHONY : maplayer.c.s

maplegend.o: maplegend.c.o
.PHONY : maplegend.o

# target to build an object file
maplegend.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplegend.c.o
.PHONY : maplegend.c.o

maplegend.i: maplegend.c.i
.PHONY : maplegend.i

# target to preprocess a source file
maplegend.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplegend.c.i
.PHONY : maplegend.c.i

maplegend.s: maplegend.c.s
.PHONY : maplegend.s

# target to generate assembly for a file
maplegend.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplegend.c.s
.PHONY : maplegend.c.s

maplexer.o: maplexer.c.o
.PHONY : maplexer.o

# target to build an object file
maplexer.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplexer.c.o
.PHONY : maplexer.c.o

maplexer.i: maplexer.c.i
.PHONY : maplexer.i

# target to preprocess a source file
maplexer.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplexer.c.i
.PHONY : maplexer.c.i

maplexer.s: maplexer.c.s
.PHONY : maplexer.s

# target to generate assembly for a file
maplexer.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplexer.c.s
.PHONY : maplexer.c.s

maplibxml2.o: maplibxml2.c.o
.PHONY : maplibxml2.o

# target to build an object file
maplibxml2.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplibxml2.c.o
.PHONY : maplibxml2.c.o

maplibxml2.i: maplibxml2.c.i
.PHONY : maplibxml2.i

# target to preprocess a source file
maplibxml2.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplibxml2.c.i
.PHONY : maplibxml2.c.i

maplibxml2.s: maplibxml2.c.s
.PHONY : maplibxml2.s

# target to generate assembly for a file
maplibxml2.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maplibxml2.c.s
.PHONY : maplibxml2.c.s

mapobject.o: mapobject.c.o
.PHONY : mapobject.o

# target to build an object file
mapobject.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapobject.c.o
.PHONY : mapobject.c.o

mapobject.i: mapobject.c.i
.PHONY : mapobject.i

# target to preprocess a source file
mapobject.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapobject.c.i
.PHONY : mapobject.c.i

mapobject.s: mapobject.c.s
.PHONY : mapobject.s

# target to generate assembly for a file
mapobject.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapobject.c.s
.PHONY : mapobject.c.s

mapogcfilter.o: mapogcfilter.c.o
.PHONY : mapogcfilter.o

# target to build an object file
mapogcfilter.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcfilter.c.o
.PHONY : mapogcfilter.c.o

mapogcfilter.i: mapogcfilter.c.i
.PHONY : mapogcfilter.i

# target to preprocess a source file
mapogcfilter.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcfilter.c.i
.PHONY : mapogcfilter.c.i

mapogcfilter.s: mapogcfilter.c.s
.PHONY : mapogcfilter.s

# target to generate assembly for a file
mapogcfilter.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcfilter.c.s
.PHONY : mapogcfilter.c.s

mapogcfiltercommon.o: mapogcfiltercommon.c.o
.PHONY : mapogcfiltercommon.o

# target to build an object file
mapogcfiltercommon.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcfiltercommon.c.o
.PHONY : mapogcfiltercommon.c.o

mapogcfiltercommon.i: mapogcfiltercommon.c.i
.PHONY : mapogcfiltercommon.i

# target to preprocess a source file
mapogcfiltercommon.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcfiltercommon.c.i
.PHONY : mapogcfiltercommon.c.i

mapogcfiltercommon.s: mapogcfiltercommon.c.s
.PHONY : mapogcfiltercommon.s

# target to generate assembly for a file
mapogcfiltercommon.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcfiltercommon.c.s
.PHONY : mapogcfiltercommon.c.s

mapogcsld.o: mapogcsld.c.o
.PHONY : mapogcsld.o

# target to build an object file
mapogcsld.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcsld.c.o
.PHONY : mapogcsld.c.o

mapogcsld.i: mapogcsld.c.i
.PHONY : mapogcsld.i

# target to preprocess a source file
mapogcsld.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcsld.c.i
.PHONY : mapogcsld.c.i

mapogcsld.s: mapogcsld.c.s
.PHONY : mapogcsld.s

# target to generate assembly for a file
mapogcsld.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcsld.c.s
.PHONY : mapogcsld.c.s

mapogcsos.o: mapogcsos.c.o
.PHONY : mapogcsos.o

# target to build an object file
mapogcsos.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcsos.c.o
.PHONY : mapogcsos.c.o

mapogcsos.i: mapogcsos.c.i
.PHONY : mapogcsos.i

# target to preprocess a source file
mapogcsos.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcsos.c.i
.PHONY : mapogcsos.c.i

mapogcsos.s: mapogcsos.c.s
.PHONY : mapogcsos.s

# target to generate assembly for a file
mapogcsos.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogcsos.c.s
.PHONY : mapogcsos.c.s

mapogr.o: mapogr.cpp.o
.PHONY : mapogr.o

# target to build an object file
mapogr.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogr.cpp.o
.PHONY : mapogr.cpp.o

mapogr.i: mapogr.cpp.i
.PHONY : mapogr.i

# target to preprocess a source file
mapogr.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogr.cpp.i
.PHONY : mapogr.cpp.i

mapogr.s: mapogr.cpp.s
.PHONY : mapogr.s

# target to generate assembly for a file
mapogr.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogr.cpp.s
.PHONY : mapogr.cpp.s

mapogroutput.o: mapogroutput.c.o
.PHONY : mapogroutput.o

# target to build an object file
mapogroutput.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogroutput.c.o
.PHONY : mapogroutput.c.o

mapogroutput.i: mapogroutput.c.i
.PHONY : mapogroutput.i

# target to preprocess a source file
mapogroutput.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogroutput.c.i
.PHONY : mapogroutput.c.i

mapogroutput.s: mapogroutput.c.s
.PHONY : mapogroutput.s

# target to generate assembly for a file
mapogroutput.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapogroutput.c.s
.PHONY : mapogroutput.c.s

maporaclespatial.o: maporaclespatial.c.o
.PHONY : maporaclespatial.o

# target to build an object file
maporaclespatial.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maporaclespatial.c.o
.PHONY : maporaclespatial.c.o

maporaclespatial.i: maporaclespatial.c.i
.PHONY : maporaclespatial.i

# target to preprocess a source file
maporaclespatial.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maporaclespatial.c.i
.PHONY : maporaclespatial.c.i

maporaclespatial.s: maporaclespatial.c.s
.PHONY : maporaclespatial.s

# target to generate assembly for a file
maporaclespatial.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maporaclespatial.c.s
.PHONY : maporaclespatial.c.s

mapoutput.o: mapoutput.c.o
.PHONY : mapoutput.o

# target to build an object file
mapoutput.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapoutput.c.o
.PHONY : mapoutput.c.o

mapoutput.i: mapoutput.c.i
.PHONY : mapoutput.i

# target to preprocess a source file
mapoutput.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapoutput.c.i
.PHONY : mapoutput.c.i

mapoutput.s: mapoutput.c.s
.PHONY : mapoutput.s

# target to generate assembly for a file
mapoutput.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapoutput.c.s
.PHONY : mapoutput.c.s

mapows.o: mapows.c.o
.PHONY : mapows.o

# target to build an object file
mapows.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapows.c.o
.PHONY : mapows.c.o

mapows.i: mapows.c.i
.PHONY : mapows.i

# target to preprocess a source file
mapows.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapows.c.i
.PHONY : mapows.c.i

mapows.s: mapows.c.s
.PHONY : mapows.s

# target to generate assembly for a file
mapows.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapows.c.s
.PHONY : mapows.c.s

mapowscommon.o: mapowscommon.c.o
.PHONY : mapowscommon.o

# target to build an object file
mapowscommon.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapowscommon.c.o
.PHONY : mapowscommon.c.o

mapowscommon.i: mapowscommon.c.i
.PHONY : mapowscommon.i

# target to preprocess a source file
mapowscommon.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapowscommon.c.i
.PHONY : mapowscommon.c.i

mapowscommon.s: mapowscommon.c.s
.PHONY : mapowscommon.s

# target to generate assembly for a file
mapowscommon.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapowscommon.c.s
.PHONY : mapowscommon.c.s

mapparser.o: mapparser.c.o
.PHONY : mapparser.o

# target to build an object file
mapparser.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapparser.c.o
.PHONY : mapparser.c.o

mapparser.i: mapparser.c.i
.PHONY : mapparser.i

# target to preprocess a source file
mapparser.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapparser.c.i
.PHONY : mapparser.c.i

mapparser.s: mapparser.c.s
.PHONY : mapparser.s

# target to generate assembly for a file
mapparser.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapparser.c.s
.PHONY : mapparser.c.s

mappluginlayer.o: mappluginlayer.c.o
.PHONY : mappluginlayer.o

# target to build an object file
mappluginlayer.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappluginlayer.c.o
.PHONY : mappluginlayer.c.o

mappluginlayer.i: mappluginlayer.c.i
.PHONY : mappluginlayer.i

# target to preprocess a source file
mappluginlayer.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappluginlayer.c.i
.PHONY : mappluginlayer.c.i

mappluginlayer.s: mappluginlayer.c.s
.PHONY : mappluginlayer.s

# target to generate assembly for a file
mappluginlayer.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappluginlayer.c.s
.PHONY : mappluginlayer.c.s

mappool.o: mappool.c.o
.PHONY : mappool.o

# target to build an object file
mappool.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappool.c.o
.PHONY : mappool.c.o

mappool.i: mappool.c.i
.PHONY : mappool.i

# target to preprocess a source file
mappool.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappool.c.i
.PHONY : mappool.c.i

mappool.s: mappool.c.s
.PHONY : mappool.s

# target to generate assembly for a file
mappool.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappool.c.s
.PHONY : mappool.c.s

mappostgis.o: mappostgis.c.o
.PHONY : mappostgis.o

# target to build an object file
mappostgis.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappostgis.c.o
.PHONY : mappostgis.c.o

mappostgis.i: mappostgis.c.i
.PHONY : mappostgis.i

# target to preprocess a source file
mappostgis.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappostgis.c.i
.PHONY : mappostgis.c.i

mappostgis.s: mappostgis.c.s
.PHONY : mappostgis.s

# target to generate assembly for a file
mappostgis.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappostgis.c.s
.PHONY : mappostgis.c.s

mappostgresql.o: mappostgresql.c.o
.PHONY : mappostgresql.o

# target to build an object file
mappostgresql.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappostgresql.c.o
.PHONY : mappostgresql.c.o

mappostgresql.i: mappostgresql.c.i
.PHONY : mappostgresql.i

# target to preprocess a source file
mappostgresql.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappostgresql.c.i
.PHONY : mappostgresql.c.i

mappostgresql.s: mappostgresql.c.s
.PHONY : mappostgresql.s

# target to generate assembly for a file
mappostgresql.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mappostgresql.c.s
.PHONY : mappostgresql.c.s

mapprimitive.o: mapprimitive.c.o
.PHONY : mapprimitive.o

# target to build an object file
mapprimitive.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapprimitive.c.o
.PHONY : mapprimitive.c.o

mapprimitive.i: mapprimitive.c.i
.PHONY : mapprimitive.i

# target to preprocess a source file
mapprimitive.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapprimitive.c.i
.PHONY : mapprimitive.c.i

mapprimitive.s: mapprimitive.c.s
.PHONY : mapprimitive.s

# target to generate assembly for a file
mapprimitive.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapprimitive.c.s
.PHONY : mapprimitive.c.s

mapproject.o: mapproject.c.o
.PHONY : mapproject.o

# target to build an object file
mapproject.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapproject.c.o
.PHONY : mapproject.c.o

mapproject.i: mapproject.c.i
.PHONY : mapproject.i

# target to preprocess a source file
mapproject.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapproject.c.i
.PHONY : mapproject.c.i

mapproject.s: mapproject.c.s
.PHONY : mapproject.s

# target to generate assembly for a file
mapproject.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapproject.c.s
.PHONY : mapproject.c.s

mapprojhack.o: mapprojhack.c.o
.PHONY : mapprojhack.o

# target to build an object file
mapprojhack.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapprojhack.c.o
.PHONY : mapprojhack.c.o

mapprojhack.i: mapprojhack.c.i
.PHONY : mapprojhack.i

# target to preprocess a source file
mapprojhack.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapprojhack.c.i
.PHONY : mapprojhack.c.i

mapprojhack.s: mapprojhack.c.s
.PHONY : mapprojhack.s

# target to generate assembly for a file
mapprojhack.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapprojhack.c.s
.PHONY : mapprojhack.c.s

mapquantization.o: mapquantization.c.o
.PHONY : mapquantization.o

# target to build an object file
mapquantization.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapquantization.c.o
.PHONY : mapquantization.c.o

mapquantization.i: mapquantization.c.i
.PHONY : mapquantization.i

# target to preprocess a source file
mapquantization.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapquantization.c.i
.PHONY : mapquantization.c.i

mapquantization.s: mapquantization.c.s
.PHONY : mapquantization.s

# target to generate assembly for a file
mapquantization.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapquantization.c.s
.PHONY : mapquantization.c.s

mapquery.o: mapquery.c.o
.PHONY : mapquery.o

# target to build an object file
mapquery.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapquery.c.o
.PHONY : mapquery.c.o

mapquery.i: mapquery.c.i
.PHONY : mapquery.i

# target to preprocess a source file
mapquery.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapquery.c.i
.PHONY : mapquery.c.i

mapquery.s: mapquery.c.s
.PHONY : mapquery.s

# target to generate assembly for a file
mapquery.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapquery.c.s
.PHONY : mapquery.c.s

mapraster.o: mapraster.c.o
.PHONY : mapraster.o

# target to build an object file
mapraster.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapraster.c.o
.PHONY : mapraster.c.o

mapraster.i: mapraster.c.i
.PHONY : mapraster.i

# target to preprocess a source file
mapraster.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapraster.c.i
.PHONY : mapraster.c.i

mapraster.s: mapraster.c.s
.PHONY : mapraster.s

# target to generate assembly for a file
mapraster.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapraster.c.s
.PHONY : mapraster.c.s

maprasterquery.o: maprasterquery.c.o
.PHONY : maprasterquery.o

# target to build an object file
maprasterquery.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maprasterquery.c.o
.PHONY : maprasterquery.c.o

maprasterquery.i: maprasterquery.c.i
.PHONY : maprasterquery.i

# target to preprocess a source file
maprasterquery.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maprasterquery.c.i
.PHONY : maprasterquery.c.i

maprasterquery.s: maprasterquery.c.s
.PHONY : maprasterquery.s

# target to generate assembly for a file
maprasterquery.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maprasterquery.c.s
.PHONY : maprasterquery.c.s

mapregex.o: mapregex.c.o
.PHONY : mapregex.o

# target to build an object file
mapregex.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapregex.c.o
.PHONY : mapregex.c.o

mapregex.i: mapregex.c.i
.PHONY : mapregex.i

# target to preprocess a source file
mapregex.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapregex.c.i
.PHONY : mapregex.c.i

mapregex.s: mapregex.c.s
.PHONY : mapregex.s

# target to generate assembly for a file
mapregex.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapregex.c.s
.PHONY : mapregex.c.s

maprendering.o: maprendering.c.o
.PHONY : maprendering.o

# target to build an object file
maprendering.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maprendering.c.o
.PHONY : maprendering.c.o

maprendering.i: maprendering.c.i
.PHONY : maprendering.i

# target to preprocess a source file
maprendering.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maprendering.c.i
.PHONY : maprendering.c.i

maprendering.s: maprendering.c.s
.PHONY : maprendering.s

# target to generate assembly for a file
maprendering.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maprendering.c.s
.PHONY : maprendering.c.s

mapresample.o: mapresample.c.o
.PHONY : mapresample.o

# target to build an object file
mapresample.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapresample.c.o
.PHONY : mapresample.c.o

mapresample.i: mapresample.c.i
.PHONY : mapresample.i

# target to preprocess a source file
mapresample.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapresample.c.i
.PHONY : mapresample.c.i

mapresample.s: mapresample.c.s
.PHONY : mapresample.s

# target to generate assembly for a file
mapresample.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapresample.c.s
.PHONY : mapresample.c.s

mapscale.o: mapscale.c.o
.PHONY : mapscale.o

# target to build an object file
mapscale.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapscale.c.o
.PHONY : mapscale.c.o

mapscale.i: mapscale.c.i
.PHONY : mapscale.i

# target to preprocess a source file
mapscale.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapscale.c.i
.PHONY : mapscale.c.i

mapscale.s: mapscale.c.s
.PHONY : mapscale.s

# target to generate assembly for a file
mapscale.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapscale.c.s
.PHONY : mapscale.c.s

mapsde.o: mapsde.c.o
.PHONY : mapsde.o

# target to build an object file
mapsde.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsde.c.o
.PHONY : mapsde.c.o

mapsde.i: mapsde.c.i
.PHONY : mapsde.i

# target to preprocess a source file
mapsde.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsde.c.i
.PHONY : mapsde.c.i

mapsde.s: mapsde.c.s
.PHONY : mapsde.s

# target to generate assembly for a file
mapsde.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsde.c.s
.PHONY : mapsde.c.s

mapsearch.o: mapsearch.c.o
.PHONY : mapsearch.o

# target to build an object file
mapsearch.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsearch.c.o
.PHONY : mapsearch.c.o

mapsearch.i: mapsearch.c.i
.PHONY : mapsearch.i

# target to preprocess a source file
mapsearch.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsearch.c.i
.PHONY : mapsearch.c.i

mapsearch.s: mapsearch.c.s
.PHONY : mapsearch.s

# target to generate assembly for a file
mapsearch.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsearch.c.s
.PHONY : mapsearch.c.s

mapserv.o: mapserv.c.o
.PHONY : mapserv.o

# target to build an object file
mapserv.c.o:
	$(MAKE) -f CMakeFiles/mapserv.dir/build.make CMakeFiles/mapserv.dir/mapserv.c.o
.PHONY : mapserv.c.o

mapserv.i: mapserv.c.i
.PHONY : mapserv.i

# target to preprocess a source file
mapserv.c.i:
	$(MAKE) -f CMakeFiles/mapserv.dir/build.make CMakeFiles/mapserv.dir/mapserv.c.i
.PHONY : mapserv.c.i

mapserv.s: mapserv.c.s
.PHONY : mapserv.s

# target to generate assembly for a file
mapserv.c.s:
	$(MAKE) -f CMakeFiles/mapserv.dir/build.make CMakeFiles/mapserv.dir/mapserv.c.s
.PHONY : mapserv.c.s

mapservutil.o: mapservutil.c.o
.PHONY : mapservutil.o

# target to build an object file
mapservutil.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapservutil.c.o
.PHONY : mapservutil.c.o

mapservutil.i: mapservutil.c.i
.PHONY : mapservutil.i

# target to preprocess a source file
mapservutil.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapservutil.c.i
.PHONY : mapservutil.c.i

mapservutil.s: mapservutil.c.s
.PHONY : mapservutil.s

# target to generate assembly for a file
mapservutil.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapservutil.c.s
.PHONY : mapservutil.c.s

mapshape.o: mapshape.c.o
.PHONY : mapshape.o

# target to build an object file
mapshape.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapshape.c.o
.PHONY : mapshape.c.o

mapshape.i: mapshape.c.i
.PHONY : mapshape.i

# target to preprocess a source file
mapshape.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapshape.c.i
.PHONY : mapshape.c.i

mapshape.s: mapshape.c.s
.PHONY : mapshape.s

# target to generate assembly for a file
mapshape.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapshape.c.s
.PHONY : mapshape.c.s

mapsmoothing.o: mapsmoothing.c.o
.PHONY : mapsmoothing.o

# target to build an object file
mapsmoothing.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsmoothing.c.o
.PHONY : mapsmoothing.c.o

mapsmoothing.i: mapsmoothing.c.i
.PHONY : mapsmoothing.i

# target to preprocess a source file
mapsmoothing.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsmoothing.c.i
.PHONY : mapsmoothing.c.i

mapsmoothing.s: mapsmoothing.c.s
.PHONY : mapsmoothing.s

# target to generate assembly for a file
mapsmoothing.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsmoothing.c.s
.PHONY : mapsmoothing.c.s

mapstring.o: mapstring.c.o
.PHONY : mapstring.o

# target to build an object file
mapstring.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapstring.c.o
.PHONY : mapstring.c.o

mapstring.i: mapstring.c.i
.PHONY : mapstring.i

# target to preprocess a source file
mapstring.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapstring.c.i
.PHONY : mapstring.c.i

mapstring.s: mapstring.c.s
.PHONY : mapstring.s

# target to generate assembly for a file
mapstring.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapstring.c.s
.PHONY : mapstring.c.s

mapsymbol.o: mapsymbol.c.o
.PHONY : mapsymbol.o

# target to build an object file
mapsymbol.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsymbol.c.o
.PHONY : mapsymbol.c.o

mapsymbol.i: mapsymbol.c.i
.PHONY : mapsymbol.i

# target to preprocess a source file
mapsymbol.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsymbol.c.i
.PHONY : mapsymbol.c.i

mapsymbol.s: mapsymbol.c.s
.PHONY : mapsymbol.s

# target to generate assembly for a file
mapsymbol.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapsymbol.c.s
.PHONY : mapsymbol.c.s

maptclutf.o: maptclutf.c.o
.PHONY : maptclutf.o

# target to build an object file
maptclutf.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptclutf.c.o
.PHONY : maptclutf.c.o

maptclutf.i: maptclutf.c.i
.PHONY : maptclutf.i

# target to preprocess a source file
maptclutf.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptclutf.c.i
.PHONY : maptclutf.c.i

maptclutf.s: maptclutf.c.s
.PHONY : maptclutf.s

# target to generate assembly for a file
maptclutf.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptclutf.c.s
.PHONY : maptclutf.c.s

maptemplate.o: maptemplate.c.o
.PHONY : maptemplate.o

# target to build an object file
maptemplate.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptemplate.c.o
.PHONY : maptemplate.c.o

maptemplate.i: maptemplate.c.i
.PHONY : maptemplate.i

# target to preprocess a source file
maptemplate.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptemplate.c.i
.PHONY : maptemplate.c.i

maptemplate.s: maptemplate.c.s
.PHONY : maptemplate.s

# target to generate assembly for a file
maptemplate.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptemplate.c.s
.PHONY : maptemplate.c.s

mapthread.o: mapthread.c.o
.PHONY : mapthread.o

# target to build an object file
mapthread.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapthread.c.o
.PHONY : mapthread.c.o

mapthread.i: mapthread.c.i
.PHONY : mapthread.i

# target to preprocess a source file
mapthread.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapthread.c.i
.PHONY : mapthread.c.i

mapthread.s: mapthread.c.s
.PHONY : mapthread.s

# target to generate assembly for a file
mapthread.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapthread.c.s
.PHONY : mapthread.c.s

maptile.o: maptile.c.o
.PHONY : maptile.o

# target to build an object file
maptile.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptile.c.o
.PHONY : maptile.c.o

maptile.i: maptile.c.i
.PHONY : maptile.i

# target to preprocess a source file
maptile.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptile.c.i
.PHONY : maptile.c.i

maptile.s: maptile.c.s
.PHONY : maptile.s

# target to generate assembly for a file
maptile.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptile.c.s
.PHONY : maptile.c.s

maptime.o: maptime.c.o
.PHONY : maptime.o

# target to build an object file
maptime.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptime.c.o
.PHONY : maptime.c.o

maptime.i: maptime.c.i
.PHONY : maptime.i

# target to preprocess a source file
maptime.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptime.c.i
.PHONY : maptime.c.i

maptime.s: maptime.c.s
.PHONY : maptime.s

# target to generate assembly for a file
maptime.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptime.c.s
.PHONY : maptime.c.s

maptree.o: maptree.c.o
.PHONY : maptree.o

# target to build an object file
maptree.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptree.c.o
.PHONY : maptree.c.o

maptree.i: maptree.c.i
.PHONY : maptree.i

# target to preprocess a source file
maptree.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptree.c.i
.PHONY : maptree.c.i

maptree.s: maptree.c.s
.PHONY : maptree.s

# target to generate assembly for a file
maptree.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maptree.c.s
.PHONY : maptree.c.s

mapunion.o: mapunion.c.o
.PHONY : mapunion.o

# target to build an object file
mapunion.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapunion.c.o
.PHONY : mapunion.c.o

mapunion.i: mapunion.c.i
.PHONY : mapunion.i

# target to preprocess a source file
mapunion.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapunion.c.i
.PHONY : mapunion.c.i

mapunion.s: mapunion.c.s
.PHONY : mapunion.s

# target to generate assembly for a file
mapunion.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapunion.c.s
.PHONY : mapunion.c.s

maputil.o: maputil.c.o
.PHONY : maputil.o

# target to build an object file
maputil.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maputil.c.o
.PHONY : maputil.c.o

maputil.i: maputil.c.i
.PHONY : maputil.i

# target to preprocess a source file
maputil.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maputil.c.i
.PHONY : maputil.c.i

maputil.s: maputil.c.s
.PHONY : maputil.s

# target to generate assembly for a file
maputil.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/maputil.c.s
.PHONY : maputil.c.s

mapuvraster.o: mapuvraster.c.o
.PHONY : mapuvraster.o

# target to build an object file
mapuvraster.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapuvraster.c.o
.PHONY : mapuvraster.c.o

mapuvraster.i: mapuvraster.c.i
.PHONY : mapuvraster.i

# target to preprocess a source file
mapuvraster.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapuvraster.c.i
.PHONY : mapuvraster.c.i

mapuvraster.s: mapuvraster.c.s
.PHONY : mapuvraster.s

# target to generate assembly for a file
mapuvraster.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapuvraster.c.s
.PHONY : mapuvraster.c.s

mapv8.o: mapv8.cpp.o
.PHONY : mapv8.o

# target to build an object file
mapv8.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapv8.cpp.o
.PHONY : mapv8.cpp.o

mapv8.i: mapv8.cpp.i
.PHONY : mapv8.i

# target to preprocess a source file
mapv8.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapv8.cpp.i
.PHONY : mapv8.cpp.i

mapv8.s: mapv8.cpp.s
.PHONY : mapv8.s

# target to generate assembly for a file
mapv8.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapv8.cpp.s
.PHONY : mapv8.cpp.s

mapwcs.o: mapwcs.c.o
.PHONY : mapwcs.o

# target to build an object file
mapwcs.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs.c.o
.PHONY : mapwcs.c.o

mapwcs.i: mapwcs.c.i
.PHONY : mapwcs.i

# target to preprocess a source file
mapwcs.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs.c.i
.PHONY : mapwcs.c.i

mapwcs.s: mapwcs.c.s
.PHONY : mapwcs.s

# target to generate assembly for a file
mapwcs.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs.c.s
.PHONY : mapwcs.c.s

mapwcs11.o: mapwcs11.c.o
.PHONY : mapwcs11.o

# target to build an object file
mapwcs11.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs11.c.o
.PHONY : mapwcs11.c.o

mapwcs11.i: mapwcs11.c.i
.PHONY : mapwcs11.i

# target to preprocess a source file
mapwcs11.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs11.c.i
.PHONY : mapwcs11.c.i

mapwcs11.s: mapwcs11.c.s
.PHONY : mapwcs11.s

# target to generate assembly for a file
mapwcs11.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs11.c.s
.PHONY : mapwcs11.c.s

mapwcs20.o: mapwcs20.c.o
.PHONY : mapwcs20.o

# target to build an object file
mapwcs20.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs20.c.o
.PHONY : mapwcs20.c.o

mapwcs20.i: mapwcs20.c.i
.PHONY : mapwcs20.i

# target to preprocess a source file
mapwcs20.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs20.c.i
.PHONY : mapwcs20.c.i

mapwcs20.s: mapwcs20.c.s
.PHONY : mapwcs20.s

# target to generate assembly for a file
mapwcs20.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwcs20.c.s
.PHONY : mapwcs20.c.s

mapwfs.o: mapwfs.c.o
.PHONY : mapwfs.o

# target to build an object file
mapwfs.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfs.c.o
.PHONY : mapwfs.c.o

mapwfs.i: mapwfs.c.i
.PHONY : mapwfs.i

# target to preprocess a source file
mapwfs.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfs.c.i
.PHONY : mapwfs.c.i

mapwfs.s: mapwfs.c.s
.PHONY : mapwfs.s

# target to generate assembly for a file
mapwfs.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfs.c.s
.PHONY : mapwfs.c.s

mapwfs11.o: mapwfs11.c.o
.PHONY : mapwfs11.o

# target to build an object file
mapwfs11.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfs11.c.o
.PHONY : mapwfs11.c.o

mapwfs11.i: mapwfs11.c.i
.PHONY : mapwfs11.i

# target to preprocess a source file
mapwfs11.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfs11.c.i
.PHONY : mapwfs11.c.i

mapwfs11.s: mapwfs11.c.s
.PHONY : mapwfs11.s

# target to generate assembly for a file
mapwfs11.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfs11.c.s
.PHONY : mapwfs11.c.s

mapwfslayer.o: mapwfslayer.c.o
.PHONY : mapwfslayer.o

# target to build an object file
mapwfslayer.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfslayer.c.o
.PHONY : mapwfslayer.c.o

mapwfslayer.i: mapwfslayer.c.i
.PHONY : mapwfslayer.i

# target to preprocess a source file
mapwfslayer.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfslayer.c.i
.PHONY : mapwfslayer.c.i

mapwfslayer.s: mapwfslayer.c.s
.PHONY : mapwfslayer.s

# target to generate assembly for a file
mapwfslayer.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwfslayer.c.s
.PHONY : mapwfslayer.c.s

mapwms.o: mapwms.c.o
.PHONY : mapwms.o

# target to build an object file
mapwms.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwms.c.o
.PHONY : mapwms.c.o

mapwms.i: mapwms.c.i
.PHONY : mapwms.i

# target to preprocess a source file
mapwms.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwms.c.i
.PHONY : mapwms.c.i

mapwms.s: mapwms.c.s
.PHONY : mapwms.s

# target to generate assembly for a file
mapwms.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwms.c.s
.PHONY : mapwms.c.s

mapwmslayer.o: mapwmslayer.c.o
.PHONY : mapwmslayer.o

# target to build an object file
mapwmslayer.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwmslayer.c.o
.PHONY : mapwmslayer.c.o

mapwmslayer.i: mapwmslayer.c.i
.PHONY : mapwmslayer.i

# target to preprocess a source file
mapwmslayer.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwmslayer.c.i
.PHONY : mapwmslayer.c.i

mapwmslayer.s: mapwmslayer.c.s
.PHONY : mapwmslayer.s

# target to generate assembly for a file
mapwmslayer.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapwmslayer.c.s
.PHONY : mapwmslayer.c.s

mapxbase.o: mapxbase.c.o
.PHONY : mapxbase.o

# target to build an object file
mapxbase.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxbase.c.o
.PHONY : mapxbase.c.o

mapxbase.i: mapxbase.c.i
.PHONY : mapxbase.i

# target to preprocess a source file
mapxbase.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxbase.c.i
.PHONY : mapxbase.c.i

mapxbase.s: mapxbase.c.s
.PHONY : mapxbase.s

# target to generate assembly for a file
mapxbase.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxbase.c.s
.PHONY : mapxbase.c.s

mapxml.o: mapxml.c.o
.PHONY : mapxml.o

# target to build an object file
mapxml.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxml.c.o
.PHONY : mapxml.c.o

mapxml.i: mapxml.c.i
.PHONY : mapxml.i

# target to preprocess a source file
mapxml.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxml.c.i
.PHONY : mapxml.c.i

mapxml.s: mapxml.c.s
.PHONY : mapxml.s

# target to generate assembly for a file
mapxml.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxml.c.s
.PHONY : mapxml.c.s

mapxmp.o: mapxmp.c.o
.PHONY : mapxmp.o

# target to build an object file
mapxmp.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxmp.c.o
.PHONY : mapxmp.c.o

mapxmp.i: mapxmp.c.i
.PHONY : mapxmp.i

# target to preprocess a source file
mapxmp.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxmp.c.i
.PHONY : mapxmp.c.i

mapxmp.s: mapxmp.c.s
.PHONY : mapxmp.s

# target to generate assembly for a file
mapxmp.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/mapxmp.c.s
.PHONY : mapxmp.c.s

msencrypt.o: msencrypt.c.o
.PHONY : msencrypt.o

# target to build an object file
msencrypt.c.o:
	$(MAKE) -f CMakeFiles/msencrypt.dir/build.make CMakeFiles/msencrypt.dir/msencrypt.c.o
.PHONY : msencrypt.c.o

msencrypt.i: msencrypt.c.i
.PHONY : msencrypt.i

# target to preprocess a source file
msencrypt.c.i:
	$(MAKE) -f CMakeFiles/msencrypt.dir/build.make CMakeFiles/msencrypt.dir/msencrypt.c.i
.PHONY : msencrypt.c.i

msencrypt.s: msencrypt.c.s
.PHONY : msencrypt.s

# target to generate assembly for a file
msencrypt.c.s:
	$(MAKE) -f CMakeFiles/msencrypt.dir/build.make CMakeFiles/msencrypt.dir/msencrypt.c.s
.PHONY : msencrypt.c.s

renderers/agg/src/agg_arc.o: renderers/agg/src/agg_arc.cpp.o
.PHONY : renderers/agg/src/agg_arc.o

# target to build an object file
renderers/agg/src/agg_arc.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_arc.cpp.o
.PHONY : renderers/agg/src/agg_arc.cpp.o

renderers/agg/src/agg_arc.i: renderers/agg/src/agg_arc.cpp.i
.PHONY : renderers/agg/src/agg_arc.i

# target to preprocess a source file
renderers/agg/src/agg_arc.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_arc.cpp.i
.PHONY : renderers/agg/src/agg_arc.cpp.i

renderers/agg/src/agg_arc.s: renderers/agg/src/agg_arc.cpp.s
.PHONY : renderers/agg/src/agg_arc.s

# target to generate assembly for a file
renderers/agg/src/agg_arc.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_arc.cpp.s
.PHONY : renderers/agg/src/agg_arc.cpp.s

renderers/agg/src/agg_curves.o: renderers/agg/src/agg_curves.cpp.o
.PHONY : renderers/agg/src/agg_curves.o

# target to build an object file
renderers/agg/src/agg_curves.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_curves.cpp.o
.PHONY : renderers/agg/src/agg_curves.cpp.o

renderers/agg/src/agg_curves.i: renderers/agg/src/agg_curves.cpp.i
.PHONY : renderers/agg/src/agg_curves.i

# target to preprocess a source file
renderers/agg/src/agg_curves.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_curves.cpp.i
.PHONY : renderers/agg/src/agg_curves.cpp.i

renderers/agg/src/agg_curves.s: renderers/agg/src/agg_curves.cpp.s
.PHONY : renderers/agg/src/agg_curves.s

# target to generate assembly for a file
renderers/agg/src/agg_curves.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_curves.cpp.s
.PHONY : renderers/agg/src/agg_curves.cpp.s

renderers/agg/src/agg_embedded_raster_fonts.o: renderers/agg/src/agg_embedded_raster_fonts.cpp.o
.PHONY : renderers/agg/src/agg_embedded_raster_fonts.o

# target to build an object file
renderers/agg/src/agg_embedded_raster_fonts.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_embedded_raster_fonts.cpp.o
.PHONY : renderers/agg/src/agg_embedded_raster_fonts.cpp.o

renderers/agg/src/agg_embedded_raster_fonts.i: renderers/agg/src/agg_embedded_raster_fonts.cpp.i
.PHONY : renderers/agg/src/agg_embedded_raster_fonts.i

# target to preprocess a source file
renderers/agg/src/agg_embedded_raster_fonts.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_embedded_raster_fonts.cpp.i
.PHONY : renderers/agg/src/agg_embedded_raster_fonts.cpp.i

renderers/agg/src/agg_embedded_raster_fonts.s: renderers/agg/src/agg_embedded_raster_fonts.cpp.s
.PHONY : renderers/agg/src/agg_embedded_raster_fonts.s

# target to generate assembly for a file
renderers/agg/src/agg_embedded_raster_fonts.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_embedded_raster_fonts.cpp.s
.PHONY : renderers/agg/src/agg_embedded_raster_fonts.cpp.s

renderers/agg/src/agg_font_freetype.o: renderers/agg/src/agg_font_freetype.cpp.o
.PHONY : renderers/agg/src/agg_font_freetype.o

# target to build an object file
renderers/agg/src/agg_font_freetype.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_font_freetype.cpp.o
.PHONY : renderers/agg/src/agg_font_freetype.cpp.o

renderers/agg/src/agg_font_freetype.i: renderers/agg/src/agg_font_freetype.cpp.i
.PHONY : renderers/agg/src/agg_font_freetype.i

# target to preprocess a source file
renderers/agg/src/agg_font_freetype.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_font_freetype.cpp.i
.PHONY : renderers/agg/src/agg_font_freetype.cpp.i

renderers/agg/src/agg_font_freetype.s: renderers/agg/src/agg_font_freetype.cpp.s
.PHONY : renderers/agg/src/agg_font_freetype.s

# target to generate assembly for a file
renderers/agg/src/agg_font_freetype.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_font_freetype.cpp.s
.PHONY : renderers/agg/src/agg_font_freetype.cpp.s

renderers/agg/src/agg_line_aa_basics.o: renderers/agg/src/agg_line_aa_basics.cpp.o
.PHONY : renderers/agg/src/agg_line_aa_basics.o

# target to build an object file
renderers/agg/src/agg_line_aa_basics.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_line_aa_basics.cpp.o
.PHONY : renderers/agg/src/agg_line_aa_basics.cpp.o

renderers/agg/src/agg_line_aa_basics.i: renderers/agg/src/agg_line_aa_basics.cpp.i
.PHONY : renderers/agg/src/agg_line_aa_basics.i

# target to preprocess a source file
renderers/agg/src/agg_line_aa_basics.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_line_aa_basics.cpp.i
.PHONY : renderers/agg/src/agg_line_aa_basics.cpp.i

renderers/agg/src/agg_line_aa_basics.s: renderers/agg/src/agg_line_aa_basics.cpp.s
.PHONY : renderers/agg/src/agg_line_aa_basics.s

# target to generate assembly for a file
renderers/agg/src/agg_line_aa_basics.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_line_aa_basics.cpp.s
.PHONY : renderers/agg/src/agg_line_aa_basics.cpp.s

renderers/agg/src/agg_trans_affine.o: renderers/agg/src/agg_trans_affine.cpp.o
.PHONY : renderers/agg/src/agg_trans_affine.o

# target to build an object file
renderers/agg/src/agg_trans_affine.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_trans_affine.cpp.o
.PHONY : renderers/agg/src/agg_trans_affine.cpp.o

renderers/agg/src/agg_trans_affine.i: renderers/agg/src/agg_trans_affine.cpp.i
.PHONY : renderers/agg/src/agg_trans_affine.i

# target to preprocess a source file
renderers/agg/src/agg_trans_affine.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_trans_affine.cpp.i
.PHONY : renderers/agg/src/agg_trans_affine.cpp.i

renderers/agg/src/agg_trans_affine.s: renderers/agg/src/agg_trans_affine.cpp.s
.PHONY : renderers/agg/src/agg_trans_affine.s

# target to generate assembly for a file
renderers/agg/src/agg_trans_affine.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_trans_affine.cpp.s
.PHONY : renderers/agg/src/agg_trans_affine.cpp.s

renderers/agg/src/agg_vcgen_contour.o: renderers/agg/src/agg_vcgen_contour.cpp.o
.PHONY : renderers/agg/src/agg_vcgen_contour.o

# target to build an object file
renderers/agg/src/agg_vcgen_contour.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_contour.cpp.o
.PHONY : renderers/agg/src/agg_vcgen_contour.cpp.o

renderers/agg/src/agg_vcgen_contour.i: renderers/agg/src/agg_vcgen_contour.cpp.i
.PHONY : renderers/agg/src/agg_vcgen_contour.i

# target to preprocess a source file
renderers/agg/src/agg_vcgen_contour.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_contour.cpp.i
.PHONY : renderers/agg/src/agg_vcgen_contour.cpp.i

renderers/agg/src/agg_vcgen_contour.s: renderers/agg/src/agg_vcgen_contour.cpp.s
.PHONY : renderers/agg/src/agg_vcgen_contour.s

# target to generate assembly for a file
renderers/agg/src/agg_vcgen_contour.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_contour.cpp.s
.PHONY : renderers/agg/src/agg_vcgen_contour.cpp.s

renderers/agg/src/agg_vcgen_dash.o: renderers/agg/src/agg_vcgen_dash.cpp.o
.PHONY : renderers/agg/src/agg_vcgen_dash.o

# target to build an object file
renderers/agg/src/agg_vcgen_dash.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_dash.cpp.o
.PHONY : renderers/agg/src/agg_vcgen_dash.cpp.o

renderers/agg/src/agg_vcgen_dash.i: renderers/agg/src/agg_vcgen_dash.cpp.i
.PHONY : renderers/agg/src/agg_vcgen_dash.i

# target to preprocess a source file
renderers/agg/src/agg_vcgen_dash.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_dash.cpp.i
.PHONY : renderers/agg/src/agg_vcgen_dash.cpp.i

renderers/agg/src/agg_vcgen_dash.s: renderers/agg/src/agg_vcgen_dash.cpp.s
.PHONY : renderers/agg/src/agg_vcgen_dash.s

# target to generate assembly for a file
renderers/agg/src/agg_vcgen_dash.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_dash.cpp.s
.PHONY : renderers/agg/src/agg_vcgen_dash.cpp.s

renderers/agg/src/agg_vcgen_stroke.o: renderers/agg/src/agg_vcgen_stroke.cpp.o
.PHONY : renderers/agg/src/agg_vcgen_stroke.o

# target to build an object file
renderers/agg/src/agg_vcgen_stroke.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_stroke.cpp.o
.PHONY : renderers/agg/src/agg_vcgen_stroke.cpp.o

renderers/agg/src/agg_vcgen_stroke.i: renderers/agg/src/agg_vcgen_stroke.cpp.i
.PHONY : renderers/agg/src/agg_vcgen_stroke.i

# target to preprocess a source file
renderers/agg/src/agg_vcgen_stroke.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_stroke.cpp.i
.PHONY : renderers/agg/src/agg_vcgen_stroke.cpp.i

renderers/agg/src/agg_vcgen_stroke.s: renderers/agg/src/agg_vcgen_stroke.cpp.s
.PHONY : renderers/agg/src/agg_vcgen_stroke.s

# target to generate assembly for a file
renderers/agg/src/agg_vcgen_stroke.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/agg_vcgen_stroke.cpp.s
.PHONY : renderers/agg/src/agg_vcgen_stroke.cpp.s

renderers/agg/src/clipper.o: renderers/agg/src/clipper.cpp.o
.PHONY : renderers/agg/src/clipper.o

# target to build an object file
renderers/agg/src/clipper.cpp.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/clipper.cpp.o
.PHONY : renderers/agg/src/clipper.cpp.o

renderers/agg/src/clipper.i: renderers/agg/src/clipper.cpp.i
.PHONY : renderers/agg/src/clipper.i

# target to preprocess a source file
renderers/agg/src/clipper.cpp.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/clipper.cpp.i
.PHONY : renderers/agg/src/clipper.cpp.i

renderers/agg/src/clipper.s: renderers/agg/src/clipper.cpp.s
.PHONY : renderers/agg/src/clipper.s

# target to generate assembly for a file
renderers/agg/src/clipper.cpp.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/renderers/agg/src/clipper.cpp.s
.PHONY : renderers/agg/src/clipper.cpp.s

scalebar.o: scalebar.c.o
.PHONY : scalebar.o

# target to build an object file
scalebar.c.o:
	$(MAKE) -f CMakeFiles/scalebar.dir/build.make CMakeFiles/scalebar.dir/scalebar.c.o
.PHONY : scalebar.c.o

scalebar.i: scalebar.c.i
.PHONY : scalebar.i

# target to preprocess a source file
scalebar.c.i:
	$(MAKE) -f CMakeFiles/scalebar.dir/build.make CMakeFiles/scalebar.dir/scalebar.c.i
.PHONY : scalebar.c.i

scalebar.s: scalebar.c.s
.PHONY : scalebar.s

# target to generate assembly for a file
scalebar.c.s:
	$(MAKE) -f CMakeFiles/scalebar.dir/build.make CMakeFiles/scalebar.dir/scalebar.c.s
.PHONY : scalebar.c.s

shp2img.o: shp2img.c.o
.PHONY : shp2img.o

# target to build an object file
shp2img.c.o:
	$(MAKE) -f CMakeFiles/shp2img.dir/build.make CMakeFiles/shp2img.dir/shp2img.c.o
.PHONY : shp2img.c.o

shp2img.i: shp2img.c.i
.PHONY : shp2img.i

# target to preprocess a source file
shp2img.c.i:
	$(MAKE) -f CMakeFiles/shp2img.dir/build.make CMakeFiles/shp2img.dir/shp2img.c.i
.PHONY : shp2img.c.i

shp2img.s: shp2img.c.s
.PHONY : shp2img.s

# target to generate assembly for a file
shp2img.c.s:
	$(MAKE) -f CMakeFiles/shp2img.dir/build.make CMakeFiles/shp2img.dir/shp2img.c.s
.PHONY : shp2img.c.s

shptree.o: shptree.c.o
.PHONY : shptree.o

# target to build an object file
shptree.c.o:
	$(MAKE) -f CMakeFiles/shptree.dir/build.make CMakeFiles/shptree.dir/shptree.c.o
.PHONY : shptree.c.o

shptree.i: shptree.c.i
.PHONY : shptree.i

# target to preprocess a source file
shptree.c.i:
	$(MAKE) -f CMakeFiles/shptree.dir/build.make CMakeFiles/shptree.dir/shptree.c.i
.PHONY : shptree.c.i

shptree.s: shptree.c.s
.PHONY : shptree.s

# target to generate assembly for a file
shptree.c.s:
	$(MAKE) -f CMakeFiles/shptree.dir/build.make CMakeFiles/shptree.dir/shptree.c.s
.PHONY : shptree.c.s

shptreevis.o: shptreevis.c.o
.PHONY : shptreevis.o

# target to build an object file
shptreevis.c.o:
	$(MAKE) -f CMakeFiles/shptreevis.dir/build.make CMakeFiles/shptreevis.dir/shptreevis.c.o
.PHONY : shptreevis.c.o

shptreevis.i: shptreevis.c.i
.PHONY : shptreevis.i

# target to preprocess a source file
shptreevis.c.i:
	$(MAKE) -f CMakeFiles/shptreevis.dir/build.make CMakeFiles/shptreevis.dir/shptreevis.c.i
.PHONY : shptreevis.c.i

shptreevis.s: shptreevis.c.s
.PHONY : shptreevis.s

# target to generate assembly for a file
shptreevis.c.s:
	$(MAKE) -f CMakeFiles/shptreevis.dir/build.make CMakeFiles/shptreevis.dir/shptreevis.c.s
.PHONY : shptreevis.c.s

sortshp.o: sortshp.c.o
.PHONY : sortshp.o

# target to build an object file
sortshp.c.o:
	$(MAKE) -f CMakeFiles/sortshp.dir/build.make CMakeFiles/sortshp.dir/sortshp.c.o
.PHONY : sortshp.c.o

sortshp.i: sortshp.c.i
.PHONY : sortshp.i

# target to preprocess a source file
sortshp.c.i:
	$(MAKE) -f CMakeFiles/sortshp.dir/build.make CMakeFiles/sortshp.dir/sortshp.c.i
.PHONY : sortshp.c.i

sortshp.s: sortshp.c.s
.PHONY : sortshp.s

# target to generate assembly for a file
sortshp.c.s:
	$(MAKE) -f CMakeFiles/sortshp.dir/build.make CMakeFiles/sortshp.dir/sortshp.c.s
.PHONY : sortshp.c.s

strptime.o: strptime.c.o
.PHONY : strptime.o

# target to build an object file
strptime.c.o:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/strptime.c.o
.PHONY : strptime.c.o

strptime.i: strptime.c.i
.PHONY : strptime.i

# target to preprocess a source file
strptime.c.i:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/strptime.c.i
.PHONY : strptime.c.i

strptime.s: strptime.c.s
.PHONY : strptime.s

# target to generate assembly for a file
strptime.c.s:
	$(MAKE) -f CMakeFiles/mapserver.dir/build.make CMakeFiles/mapserver.dir/strptime.c.s
.PHONY : strptime.c.s

tile4ms.o: tile4ms.c.o
.PHONY : tile4ms.o

# target to build an object file
tile4ms.c.o:
	$(MAKE) -f CMakeFiles/tile4ms.dir/build.make CMakeFiles/tile4ms.dir/tile4ms.c.o
.PHONY : tile4ms.c.o

tile4ms.i: tile4ms.c.i
.PHONY : tile4ms.i

# target to preprocess a source file
tile4ms.c.i:
	$(MAKE) -f CMakeFiles/tile4ms.dir/build.make CMakeFiles/tile4ms.dir/tile4ms.c.i
.PHONY : tile4ms.c.i

tile4ms.s: tile4ms.c.s
.PHONY : tile4ms.s

# target to generate assembly for a file
tile4ms.c.s:
	$(MAKE) -f CMakeFiles/tile4ms.dir/build.make CMakeFiles/tile4ms.dir/tile4ms.c.s
.PHONY : tile4ms.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... legend"
	@echo "... list_install_components"
	@echo "... mapserv"
	@echo "... mapserver"
	@echo "... msencrypt"
	@echo "... rebuild_cache"
	@echo "... scalebar"
	@echo "... shp2img"
	@echo "... shptree"
	@echo "... shptreevis"
	@echo "... sortshp"
	@echo "... tile4ms"
	@echo "... _pythonmapscript"
	@echo "... cgiutil.o"
	@echo "... cgiutil.i"
	@echo "... cgiutil.s"
	@echo "... classobject.o"
	@echo "... classobject.i"
	@echo "... classobject.s"
	@echo "... hittest.o"
	@echo "... hittest.i"
	@echo "... hittest.s"
	@echo "... layerobject.o"
	@echo "... layerobject.i"
	@echo "... layerobject.s"
	@echo "... legend.o"
	@echo "... legend.i"
	@echo "... legend.s"
	@echo "... mapagg.o"
	@echo "... mapagg.i"
	@echo "... mapagg.s"
	@echo "... mapbits.o"
	@echo "... mapbits.i"
	@echo "... mapbits.s"
	@echo "... mapcairo.o"
	@echo "... mapcairo.i"
	@echo "... mapcairo.s"
	@echo "... mapchart.o"
	@echo "... mapchart.i"
	@echo "... mapchart.s"
	@echo "... mapcluster.o"
	@echo "... mapcluster.i"
	@echo "... mapcluster.s"
	@echo "... mapcontext.o"
	@echo "... mapcontext.i"
	@echo "... mapcontext.s"
	@echo "... mapcontour.o"
	@echo "... mapcontour.i"
	@echo "... mapcontour.s"
	@echo "... mapcopy.o"
	@echo "... mapcopy.i"
	@echo "... mapcopy.s"
	@echo "... mapcpl.o"
	@echo "... mapcpl.i"
	@echo "... mapcpl.s"
	@echo "... mapcrypto.o"
	@echo "... mapcrypto.i"
	@echo "... mapcrypto.s"
	@echo "... mapdebug.o"
	@echo "... mapdebug.i"
	@echo "... mapdebug.s"
	@echo "... mapdraw.o"
	@echo "... mapdraw.i"
	@echo "... mapdraw.s"
	@echo "... mapdrawgdal.o"
	@echo "... mapdrawgdal.i"
	@echo "... mapdrawgdal.s"
	@echo "... mapdummyrenderer.o"
	@echo "... mapdummyrenderer.i"
	@echo "... mapdummyrenderer.s"
	@echo "... maperror.o"
	@echo "... maperror.i"
	@echo "... maperror.s"
	@echo "... mapfile.o"
	@echo "... mapfile.i"
	@echo "... mapfile.s"
	@echo "... mapgd.o"
	@echo "... mapgd.i"
	@echo "... mapgd.s"
	@echo "... mapgdal.o"
	@echo "... mapgdal.i"
	@echo "... mapgdal.s"
	@echo "... mapgeomtransform.o"
	@echo "... mapgeomtransform.i"
	@echo "... mapgeomtransform.s"
	@echo "... mapgeomutil.o"
	@echo "... mapgeomutil.i"
	@echo "... mapgeomutil.s"
	@echo "... mapgeos.o"
	@echo "... mapgeos.i"
	@echo "... mapgeos.s"
	@echo "... mapgml.o"
	@echo "... mapgml.i"
	@echo "... mapgml.s"
	@echo "... mapgraticule.o"
	@echo "... mapgraticule.i"
	@echo "... mapgraticule.s"
	@echo "... maphash.o"
	@echo "... maphash.i"
	@echo "... maphash.s"
	@echo "... maphttp.o"
	@echo "... maphttp.i"
	@echo "... maphttp.s"
	@echo "... mapimageio.o"
	@echo "... mapimageio.i"
	@echo "... mapimageio.s"
	@echo "... mapimagemap.o"
	@echo "... mapimagemap.i"
	@echo "... mapimagemap.s"
	@echo "... mapio.o"
	@echo "... mapio.i"
	@echo "... mapio.s"
	@echo "... mapjoin.o"
	@echo "... mapjoin.i"
	@echo "... mapjoin.s"
	@echo "... mapkml.o"
	@echo "... mapkml.i"
	@echo "... mapkml.s"
	@echo "... mapkmlrenderer.o"
	@echo "... mapkmlrenderer.i"
	@echo "... mapkmlrenderer.s"
	@echo "... maplabel.o"
	@echo "... maplabel.i"
	@echo "... maplabel.s"
	@echo "... maplayer.o"
	@echo "... maplayer.i"
	@echo "... maplayer.s"
	@echo "... maplegend.o"
	@echo "... maplegend.i"
	@echo "... maplegend.s"
	@echo "... maplexer.o"
	@echo "... maplexer.i"
	@echo "... maplexer.s"
	@echo "... maplibxml2.o"
	@echo "... maplibxml2.i"
	@echo "... maplibxml2.s"
	@echo "... mapobject.o"
	@echo "... mapobject.i"
	@echo "... mapobject.s"
	@echo "... mapogcfilter.o"
	@echo "... mapogcfilter.i"
	@echo "... mapogcfilter.s"
	@echo "... mapogcfiltercommon.o"
	@echo "... mapogcfiltercommon.i"
	@echo "... mapogcfiltercommon.s"
	@echo "... mapogcsld.o"
	@echo "... mapogcsld.i"
	@echo "... mapogcsld.s"
	@echo "... mapogcsos.o"
	@echo "... mapogcsos.i"
	@echo "... mapogcsos.s"
	@echo "... mapogr.o"
	@echo "... mapogr.i"
	@echo "... mapogr.s"
	@echo "... mapogroutput.o"
	@echo "... mapogroutput.i"
	@echo "... mapogroutput.s"
	@echo "... maporaclespatial.o"
	@echo "... maporaclespatial.i"
	@echo "... maporaclespatial.s"
	@echo "... mapoutput.o"
	@echo "... mapoutput.i"
	@echo "... mapoutput.s"
	@echo "... mapows.o"
	@echo "... mapows.i"
	@echo "... mapows.s"
	@echo "... mapowscommon.o"
	@echo "... mapowscommon.i"
	@echo "... mapowscommon.s"
	@echo "... mapparser.o"
	@echo "... mapparser.i"
	@echo "... mapparser.s"
	@echo "... mappluginlayer.o"
	@echo "... mappluginlayer.i"
	@echo "... mappluginlayer.s"
	@echo "... mappool.o"
	@echo "... mappool.i"
	@echo "... mappool.s"
	@echo "... mappostgis.o"
	@echo "... mappostgis.i"
	@echo "... mappostgis.s"
	@echo "... mappostgresql.o"
	@echo "... mappostgresql.i"
	@echo "... mappostgresql.s"
	@echo "... mapprimitive.o"
	@echo "... mapprimitive.i"
	@echo "... mapprimitive.s"
	@echo "... mapproject.o"
	@echo "... mapproject.i"
	@echo "... mapproject.s"
	@echo "... mapprojhack.o"
	@echo "... mapprojhack.i"
	@echo "... mapprojhack.s"
	@echo "... mapquantization.o"
	@echo "... mapquantization.i"
	@echo "... mapquantization.s"
	@echo "... mapquery.o"
	@echo "... mapquery.i"
	@echo "... mapquery.s"
	@echo "... mapraster.o"
	@echo "... mapraster.i"
	@echo "... mapraster.s"
	@echo "... maprasterquery.o"
	@echo "... maprasterquery.i"
	@echo "... maprasterquery.s"
	@echo "... mapregex.o"
	@echo "... mapregex.i"
	@echo "... mapregex.s"
	@echo "... maprendering.o"
	@echo "... maprendering.i"
	@echo "... maprendering.s"
	@echo "... mapresample.o"
	@echo "... mapresample.i"
	@echo "... mapresample.s"
	@echo "... mapscale.o"
	@echo "... mapscale.i"
	@echo "... mapscale.s"
	@echo "... mapsde.o"
	@echo "... mapsde.i"
	@echo "... mapsde.s"
	@echo "... mapsearch.o"
	@echo "... mapsearch.i"
	@echo "... mapsearch.s"
	@echo "... mapserv.o"
	@echo "... mapserv.i"
	@echo "... mapserv.s"
	@echo "... mapservutil.o"
	@echo "... mapservutil.i"
	@echo "... mapservutil.s"
	@echo "... mapshape.o"
	@echo "... mapshape.i"
	@echo "... mapshape.s"
	@echo "... mapsmoothing.o"
	@echo "... mapsmoothing.i"
	@echo "... mapsmoothing.s"
	@echo "... mapstring.o"
	@echo "... mapstring.i"
	@echo "... mapstring.s"
	@echo "... mapsymbol.o"
	@echo "... mapsymbol.i"
	@echo "... mapsymbol.s"
	@echo "... maptclutf.o"
	@echo "... maptclutf.i"
	@echo "... maptclutf.s"
	@echo "... maptemplate.o"
	@echo "... maptemplate.i"
	@echo "... maptemplate.s"
	@echo "... mapthread.o"
	@echo "... mapthread.i"
	@echo "... mapthread.s"
	@echo "... maptile.o"
	@echo "... maptile.i"
	@echo "... maptile.s"
	@echo "... maptime.o"
	@echo "... maptime.i"
	@echo "... maptime.s"
	@echo "... maptree.o"
	@echo "... maptree.i"
	@echo "... maptree.s"
	@echo "... mapunion.o"
	@echo "... mapunion.i"
	@echo "... mapunion.s"
	@echo "... maputil.o"
	@echo "... maputil.i"
	@echo "... maputil.s"
	@echo "... mapuvraster.o"
	@echo "... mapuvraster.i"
	@echo "... mapuvraster.s"
	@echo "... mapv8.o"
	@echo "... mapv8.i"
	@echo "... mapv8.s"
	@echo "... mapwcs.o"
	@echo "... mapwcs.i"
	@echo "... mapwcs.s"
	@echo "... mapwcs11.o"
	@echo "... mapwcs11.i"
	@echo "... mapwcs11.s"
	@echo "... mapwcs20.o"
	@echo "... mapwcs20.i"
	@echo "... mapwcs20.s"
	@echo "... mapwfs.o"
	@echo "... mapwfs.i"
	@echo "... mapwfs.s"
	@echo "... mapwfs11.o"
	@echo "... mapwfs11.i"
	@echo "... mapwfs11.s"
	@echo "... mapwfslayer.o"
	@echo "... mapwfslayer.i"
	@echo "... mapwfslayer.s"
	@echo "... mapwms.o"
	@echo "... mapwms.i"
	@echo "... mapwms.s"
	@echo "... mapwmslayer.o"
	@echo "... mapwmslayer.i"
	@echo "... mapwmslayer.s"
	@echo "... mapxbase.o"
	@echo "... mapxbase.i"
	@echo "... mapxbase.s"
	@echo "... mapxml.o"
	@echo "... mapxml.i"
	@echo "... mapxml.s"
	@echo "... mapxmp.o"
	@echo "... mapxmp.i"
	@echo "... mapxmp.s"
	@echo "... msencrypt.o"
	@echo "... msencrypt.i"
	@echo "... msencrypt.s"
	@echo "... renderers/agg/src/agg_arc.o"
	@echo "... renderers/agg/src/agg_arc.i"
	@echo "... renderers/agg/src/agg_arc.s"
	@echo "... renderers/agg/src/agg_curves.o"
	@echo "... renderers/agg/src/agg_curves.i"
	@echo "... renderers/agg/src/agg_curves.s"
	@echo "... renderers/agg/src/agg_embedded_raster_fonts.o"
	@echo "... renderers/agg/src/agg_embedded_raster_fonts.i"
	@echo "... renderers/agg/src/agg_embedded_raster_fonts.s"
	@echo "... renderers/agg/src/agg_font_freetype.o"
	@echo "... renderers/agg/src/agg_font_freetype.i"
	@echo "... renderers/agg/src/agg_font_freetype.s"
	@echo "... renderers/agg/src/agg_line_aa_basics.o"
	@echo "... renderers/agg/src/agg_line_aa_basics.i"
	@echo "... renderers/agg/src/agg_line_aa_basics.s"
	@echo "... renderers/agg/src/agg_trans_affine.o"
	@echo "... renderers/agg/src/agg_trans_affine.i"
	@echo "... renderers/agg/src/agg_trans_affine.s"
	@echo "... renderers/agg/src/agg_vcgen_contour.o"
	@echo "... renderers/agg/src/agg_vcgen_contour.i"
	@echo "... renderers/agg/src/agg_vcgen_contour.s"
	@echo "... renderers/agg/src/agg_vcgen_dash.o"
	@echo "... renderers/agg/src/agg_vcgen_dash.i"
	@echo "... renderers/agg/src/agg_vcgen_dash.s"
	@echo "... renderers/agg/src/agg_vcgen_stroke.o"
	@echo "... renderers/agg/src/agg_vcgen_stroke.i"
	@echo "... renderers/agg/src/agg_vcgen_stroke.s"
	@echo "... renderers/agg/src/clipper.o"
	@echo "... renderers/agg/src/clipper.i"
	@echo "... renderers/agg/src/clipper.s"
	@echo "... scalebar.o"
	@echo "... scalebar.i"
	@echo "... scalebar.s"
	@echo "... shp2img.o"
	@echo "... shp2img.i"
	@echo "... shp2img.s"
	@echo "... shptree.o"
	@echo "... shptree.i"
	@echo "... shptree.s"
	@echo "... shptreevis.o"
	@echo "... shptreevis.i"
	@echo "... shptreevis.s"
	@echo "... sortshp.o"
	@echo "... sortshp.i"
	@echo "... sortshp.s"
	@echo "... strptime.o"
	@echo "... strptime.i"
	@echo "... strptime.s"
	@echo "... tile4ms.o"
	@echo "... tile4ms.i"
	@echo "... tile4ms.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

